[rocm-libraries] ROCm/rocm-libraries#4454 (commit a144e76)
feat(rocrand): use primbench
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

## Motivation

rocRAND's benchmarks have been updated to use
[primbench](https://github.com/ROCm/rocm-libraries/tree/develop/shared/primbench).
This makes the benchmark results more accurate than was previously
possible with Google Benchmark.

To guarantee the correctness of the benchmarks I have added the commit
[feat(primbench): built-in correctness
assertions](https://github.com/ROCm/rocm-libraries/pull/4454/changes/3804604be0fb5751ad9aad13f0f3ffb94e376698)
for primbench. rocRAND's benchmarks use it to verify that the mean and
standard deviation of all
[device](https://github.com/ROCm/rocm-libraries/pull/4454/changes/0f046812bfe824fc1d7c29e689e7ea0ae41f0b84)
and
[host](https://github.com/ROCm/rocm-libraries/pull/4454/changes/dc61a479d6dc7e4e71f902bf60e2c3c8cb593f6f)
benchmark specializations is correct.

JIRA ID : ROCM-27414

## Technical Details

> [!WARNING]
> AMD's CI team must install AMD SMI before this PR can be merged.
>
> The `Linux (hiprand,rocrand | gfx94X-dcgpu) / Build (gfx94X-dcgpu)`
job its `Build therock-archives and therock-dist` step fails, which is
most likely because AMD SMI is not (properly) installed in rocRAND's CI
image yet:
> ```
> [rocRAND]
/__w/rocm-libraries/rocm-libraries/projects/rocrand/../../shared/primbench/primbench.hpp:50:18:
fatal error: 'amd_smi/amdsmi.h' file not found
> [rocRAND]    50 |         #include <amd_smi/amdsmi.h>
> [rocRAND]       |                  ^~~~~~~~~~~~~~~~~~
> ```

> [!NOTE]
> If AMD's GPU cooling setup is too weak or too powerful then
`--min-gpu-temp` (default 50°C) or `--max-gpu-temp` (default 60°C) will
need to be passed to benchmarks by AMD's CI. I recommend holding off on
passing these flags until a benchmark _actually_ times out from not
reaching the 50°C-60°C temperature range.

This PR updates `primbench.hpp` to support CLI options that take an
array of values. This allows passing `--lambda 4 2` to
`benchmark_rocrand_host_api` to still work.

The old code its `--size <N>` flag allowed users to pass `--byte-size`.
This let `N` represent the number of bytes, rather than the number of
items. This `--byte-size` flag has been removed to simplify the code,
but it can be reintroduced if we know *anyone* who still needs it.

## Removal of legacy rocRAND benchmarks for ROCm 8.0

This PR should be merged into ROCm 8.0, as these legacy rocRAND
benchmarks have been removed:
- `benchmark_curand_generate`
- `benchmark_curand_kernel`
- `benchmark_rocrand_generate`
- `benchmark_rocrand_kernel`

The `Legacy benchmarks` header in rocRAND's readme
[here](https://github.com/ROCm/rocm-libraries/blob/ff67c176e9c9d1d2d7fe615a6179cf2fb422aa11/projects/rocrand/README.md#legacy-benchmarks)
states that these benchmarks were already deprecated:

> You can disable legacy benchmarks (those used prior to Google
Benchmark) by setting the
> CMake option `BUILD_LEGACY_BENCHMARK` to `OFF`. For compatibility, the
default setting is `ON`
> when `BUILD_BENCHMARK` is set.
>
> Legacy benchmarks are deprecated and will be removed in a future
version once all benchmarks have
been migrated to the new framework.

The old changelog entry `rocRAND-2.10.17 for ROCm 5.5.0` explains why
they were deprecated:
> * New benchmark APIs for Google Benchmark:
>   * `benchmark_rocrand_device_api` replaces `benchmark_rocrand_kernel`
>   * `benchmark_curand_host_api` replaces `benchmark_curand_generate`
>   * `benchmark_curand_device_api` replaces `benchmark_curand_kernel`

## Test Plan

The below blocks of commands can be copied directly into a terminal, so
you don't need to copy the lines individually.

See the `Test Result` header in this description for the zip that
contains all of the scripts that these reproduction steps use.

### VS Code dev containers

<details>
<summary>HIP <code>Dockerfile</code> +
<code>devcontainer.json</code></summary>

`Dockerfile`:
```Dockerfile
FROM rocm/rocm-terminal:latest
```

`devcontainer.json`:
```json
{
    "build": {
        "dockerfile": "Dockerfile"
    },
    "name": "hip-minimal",
    "runArgs": [
        "--device=/dev/kfd",
        "--device=/dev/dri"
    ]
}
```

</details>

<details>
<summary>CUDA <code>Dockerfile</code> +
<code>devcontainer.json</code></summary>

`Dockerfile`:
```Dockerfile
FROM nvidia/cuda:12.9.1-devel-ubuntu24.04

RUN apt update && apt install -y git cmake ninja-build wget

RUN wget -qO- https://repo.radeon.com/rocm/rocm.gpg.key | gpg --dearmor > /etc/apt/keyrings/rocm.gpg

RUN echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/rocm.gpg] https://repo.radeon.com/rocm/apt/7.2 noble main" > /etc/apt/sources.list.d/rocm.list

RUN tee /etc/apt/preferences.d/rocm-pin-600 <<'EOF'
Package: *
Pin: origin repo.radeon.com
Pin-Priority: 600
EOF

RUN apt update && apt install -y hip-base

ENV HIP_PLATFORM=nvidia
```

`devcontainer.json`:
```json
{
    "build": {
        "dockerfile": "Dockerfile"
    },
    "name": "cuda-minimal",
    "privileged": true,
    "runArgs": [
        "--gpus=all"
    ]
}
```

</details>

### Reproduction steps

> [!IMPORTANT]
> AMD should confirm that these reproduction steps for running the
rocRAND benchmarks work on Windows, since Stream HPC's Windows CI is
currently broken.

<details>
<summary>Installing dependencies</summary>

```sh
sudo apt update && \
sudo apt install -y cmake ninja-build
```

</details>

<details>
<summary>Cloning</summary>

```sh
git clone --no-checkout --filter=blob:none https://github.com/ROCm/rocm-libraries.git && \
cd rocm-libraries && \
git sparse-checkout init --cone && \
git sparse-checkout set projects/rocrand shared/primbench
```

</details>

<details>
<summary>Building primbench benchmarks</summary>

#### Setup

```sh
git checkout users/mynameistrez/use-primbench-in-rocrand && \
cd projects/rocrand && \
mkdir build_benchmark_primbench && \
cd build_benchmark_primbench
```

#### HIP

```sh
export gfx=$(rocm_agent_enumerator | head -n1) && \
CXX=hipcc cmake -GNinja -DBUILD_BENCHMARK=ON -DGPU_TARGETS="$gfx" .. && \
ninja benchmark_host_api benchmark_device_api
```

#### CUDA

```sh
cmake -GNinja -DBUILD_BENCHMARK=ON .. && \
ninja benchmark_host_api benchmark_device_api
```

</details>

<details>
<summary>Running primbench benchmarks</summary>

#### HIP

```sh
benchmark/benchmark_device_api \
  --json-out benchmark_rocrand_device_api.json \
  --csv-out benchmark_rocrand_device_api.csv
```
```sh
benchmark/benchmark_host_api \
  --json-out benchmark_rocrand_host_api.json \
  --csv-out benchmark_rocrand_host_api.csv
```

#### CUDA

```sh
benchmark/benchmark_device_api \
  --json-out benchmark_curand_device_api.json \
  --csv-out benchmark_curand_device_api.csv
```
```sh
benchmark/benchmark_host_api \
  --json-out benchmark_curand_host_api.json \
  --csv-out benchmark_curand_host_api.csv
```

</details>

<details>
<summary>Building develop benchmarks</summary>

#### Setup

```sh
git checkout ead5d115 && \
cd projects/rocrand && \
mkdir build_benchmark_develop && \
cd build_benchmark_develop
```

#### HIP

```sh
export gfx=$(rocm_agent_enumerator | head -n1) && \
CXX=hipcc cmake -GNinja -DBUILD_BENCHMARK=ON -DGPU_TARGETS="$gfx" .. && \
ninja benchmark_rocrand_host_api benchmark_rocrand_device_api
```

#### CUDA

```sh
cmake -GNinja -DBUILD_BENCHMARK=ON .. && \
ninja benchmark_curand_host_api benchmark_curand_device_api
```

</details>

<details>
<summary>Running develop benchmarks</summary>

#### HIP

```sh
benchmark/benchmark_rocrand_device_api \
  --benchmark_out=benchmark_rocrand_device_api.json
```
```sh
benchmark/benchmark_rocrand_host_api \
  --benchmark_out=benchmark_rocrand_host_api.json
```

#### CUDA

```sh
benchmark/benchmark_curand_device_api \
  --benchmark_out=benchmark_curand_device_api.json
```
```sh
benchmark/benchmark_curand_host_api \
  --benchmark_out=benchmark_curand_host_api.json
```

</details>

<details>
<summary>Converting develop JSON results to primbench CSVs</summary>

The script `gbench2primbench.py` converts a directory of old Google
Benchmark JSON files to a directory of new primbench CSV files.

<details><summary><code>--help</code> options</summary>

```
usage: gbench2primbench.py [-h] --project {rocprim,rocrand} --noise-threshold-percentage NOISE_THRESHOLD_PERCENTAGE input_dir output_dir

Convert Google Benchmark JSON to primbench CSV format

positional arguments:
  input_dir             Directory containing Google Benchmark JSON files
  output_dir            Output directory for primbench CSV files

options:
  -h, --help            show this help message and exit
  --project {rocprim,rocrand}
                        Project name
  --noise-threshold-percentage NOISE_THRESHOLD_PERCENTAGE
                        The noise threshold percentage, past which benchmark specializations are considered to be too noisy
```

</details>

```sh
python3 gbench2primbench.py \
  --project rocrand \
  --noise-threshold-percentage 1 \
  build_benchmark_develop/results \
  converted
```

</details>

<details>
<summary>Generating graphs</summary>

The script `grapher.py` takes primbench JSON and CSV files, and
generates a relative or absolute graph.

In the previous step `gbench2primbench.py` was used to convert old
Google Benchmark JSON files to primbench CSV files.

The zip of the results contains both relative and absolute graphs, where
the absolute graphs were generated by passing `--absolute` to
`grapher.py`.

<details><summary><code>--help</code> options</summary>

```
Usage: grapher.py [-h] --output OUTPUT [--algo ALGO] [--arch ARCH] [--filter FILTER] [--absolute] input_files [input_files ...]

Positional Arguments:
  input_files      paths to input .json or .csv primbench files

Options:
  -h, --help       show this help message and exit
  --output OUTPUT  path to output .svg graph (default: None)
  --algo ALGO      algorithm name for the chart title (required if only CSV files are passed) (default: None)
  --arch ARCH      GPU arch name for the chart title (required if only CSV files are passed) (default: None)
  --filter FILTER  regex pattern of specializations to include (default: None)
  --absolute       perform absolute instead of relative comparison (default: False)
```

</details>

```sh
python3 -m pip install numpy pygal pandas rich_argparse scipy && \
for csv in converted/*.csv; do
  b=$(basename "$csv" .csv)
  python3 grapher.py \
    --output "graphs/$b.svg" \
    "converted/$b.csv" \
    "build_benchmark_primbench/results/json/$b.json"
done
```

</details>

<details>
<summary>Tuning rocRAND</summary>

#### Building

```sh
git checkout users/mynameistrez/use-primbench-in-rocrand && \
cd projects/rocrand && \
mkdir build_tuning && \
cd build_tuning && \
export gfx=$(rocm_agent_enumerator | head -n1) && \
CXX=hipcc cmake -GNinja -DBUILD_BENCHMARK=ON -DBUILD_BENCHMARK_TUNING=ON -DGPU_TARGETS="$gfx" .. && \
ninja benchmark_rocrand_tuning
```

#### Running in primbench

##### Minimal command

```sh
benchmark/benchmark_rocrand_tuning \
  --json-out tuning_primbench.json
```

##### Running as a background process

```sh
nohup timeout 24h bash -c '
  time benchmark/benchmark_rocrand_tuning \
    --json-out tuning_primbench.json
' >benchmark.log 2>&1 &
```

#### Running in develop

##### Minimal command

```sh
benchmark/tuning/benchmark_rocrand_tuning && \
  --benchmark_out=tuning_develop.json
```

##### Running as a background process

```sh
nohup timeout 24h bash -c '
  time benchmark/tuning/benchmark_rocrand_tuning \
  --benchmark_out=tuning_develop.json
' >benchmark.log 2>&1 &
```

</details>

<details>
<summary>Generating configs</summary>

#### Setup

```sh
python3 -m venv .venv && \
source .venv/bin/activate && \
python3 -m pip install -r scripts/config-tuning/requirements.in
```

#### Generating the default config

##### For primbench

```sh
mkdir -p primbench_configs/ && \
python3 scripts/config-tuning/generate_config_defaults.py \
  --out-dir primbench_configs/ \
  --in-dir scripts/config-tuning/
```

##### For develop

```sh
mkdir -p develop_configs/ && \
python3 scripts/config-tuning/generate_config_defaults.py \
  --out-dir develop_configs/ \
  --in-dir scripts/config-tuning/
```

#### Generating tuned configs

##### For primbench

```sh
mkdir -p primbench_configs/ && \
python3 scripts/config-tuning/select_best_config.py \
  --out-dir primbench_configs/ \
  tuning_primbench.json
```

##### For develop

```sh
mkdir -p develop_configs/ && \
python3 scripts/config-tuning/select_best_config.py \
  --out-dir develop_configs/ \
  tuning_develop.json
```

#### Diffing develop against primbench configs

```sh
diff develop_configs primbench_configs
```

</details>

## Test Result

There are basically no regressions nor noise timeouts.

Paul Kliemann is working on publishing a primbench PR in the coming
weeks that significantly lowers the noise of benchmark specializations,
by calculating entropy instead. rocRAND will automatically benefit from
it.

## Submission Checklist

- [x] Look over the contributing guidelines at
https://github.com/ROCm/ROCm/blob/develop/CONTRIBUTING.md#pull-requests.